---
# iam tasks. Seperated due to permissions to our own accounts

- name: create iam role for bucket replication
  iam_role:
    aws_access_key: "{{ iam_aws_access_key }}"
    aws_secret_key: "{{ iam_aws_secret_key }}"
    security_token: "{{ iam_security_token }}"
    name: "{{ iam_role_name }}"
    assume_role_policy_document: "{{ lookup('file','role-policy.json') }}"
    state: present

- name: create replication policy from template
  iam_policy:
    aws_access_key: "{{ iam_aws_access_key }}"
    aws_secret_key: "{{ iam_aws_secret_key }}"
    security_token: "{{ iam_security_token }}"
    iam_type: role
    iam_name: "{{ iam_role_name }}"
    policy_name: "{{ iam_policy_name }}"
    state: present
    policy_json: "{{ lookup('template', 'replication-policy.json.j2') }}